# Generated by Django 5.0.1 on 2024-01-23 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpcModelSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=5000, null=True)),
                ('text_body', models.CharField(blank=True, max_length=5000, null=True)),
                ('edition', models.CharField(blank=True, max_length=5000, null=True)),
                ('ref', models.CharField(blank=True, max_length=5000, null=True)),
                ('section', models.CharField(blank=True, max_length=5000, null=True)),
                ('main_class', models.CharField(blank=True, max_length=5000, null=True)),
                ('subclass', models.CharField(blank=True, max_length=5000, null=True)),
                ('main_group', models.CharField(blank=True, max_length=5000, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_title', models.CharField(max_length=120)),
                ('patent_owner', models.CharField(max_length=120)),
                ('patent_description', models.CharField(max_length=2000)),
                ('patent_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
